modLoader="javafml"
license="Apache-2.0"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/issues"

[[mods]]
modId="advanced_solars"
version="${version}"
displayName="Advanced Solars Classic"
displayURL="https://github.com/Trins-mods/Advanced-Solars-Classic-Edition"
credits="Speiger for ic2 classic, author of advanced solars original for the original."
authors="Trinsdar"
description='''Advanced Solars for Ic2 classic.'''
[[dependencies.advanced_solars]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.34,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.advanced_solars]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.advanced_solars]]
    modId="ic2"
    mandatory=true
    versionRange="[1.19.2-2.0.7,)"
    ordering="AFTER"
    side="BOTH"